In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))

In [7]:
import os

img_dir = Path("../data/raw/VOCtrainval-2007/JPEGImages")
img_list = os.listdir(img_dir)

annot_dir = Path("../data/raw/VOCtrainval-2007/Annotations")
annot_list = os.listdir(annot_dir)

img_list[:5], annot_list[:5]

(['000005.jpg', '000007.jpg', '000009.jpg', '000012.jpg', '000016.jpg'],
 ['000005.xml', '000007.xml', '000009.xml', '000012.xml', '000016.xml'])

### Cleaner XML Parsing

In [3]:
import xml.etree.ElementTree as ET

tree = ET.parse(os.path.join(annot_dir, annot_list[0]))
root = tree.getroot()

root.tag, root.attrib

('annotation', {})

In [4]:
filename = root.find("filename").text
filename

'000005.jpg'

In [5]:
from src.configs import IMAGE_SIZE

size = root.find("size")
width = int(size.find("width").text)
height = int(size.find("height").text)
img_width_ratio = IMAGE_SIZE / width
img_height_ratio = IMAGE_SIZE / height

print(width, height, img_width_ratio, img_height_ratio)

500 375 0.448 0.5973333333333334

In [32]:
import numpy as np

objects = []

for obj in root.findall("object"):
    class_name = obj.find("name").text
    
    bndbox = obj.find("bndbox")
    xmin = int(bndbox.find("xmin").text) * img_width_ratio
    ymin = int(bndbox.find("ymin").text) * img_height_ratio
    xmax = int(bndbox.find("xmax").text) * img_width_ratio
    ymax = int(bndbox.find("ymax").text) * img_height_ratio

    center = (np.mean([xmin, xmax]), np.mean([ymin, ymax]))
    width = (xmax - xmin)
    height = (ymax - ymin) 
    
    objects.append((class_name, center[0], center[1], width, height))
    
objects

[('chair',
  np.float64(131.488),
  np.float64(164.26666666666668),
  27.328000000000017,
  76.45866666666666),
 ('chair',
  np.float64(93.632),
  np.float64(189.95200000000003),
  39.42400000000001,
  64.512),
 ('chair',
  np.float64(16.128),
  np.float64(184.57600000000002),
  27.776000000000003,
  77.65333333333334),
 ('chair',
  np.float64(120.064),
  np.float64(147.24266666666668),
  24.191999999999993,
  62.72000000000001),
 ('chair',
  np.float64(131.936),
  np.float64(121.25866666666668),
  15.680000000000007,
  20.309333333333342)]

### Visualize Pandas Read CSV Dataframe

In [42]:
import pandas as pd

annotations_file = Path("../data/preprocessed/trainval/annotations.csv")
df = pd.read_csv(annotations_file)

df

         filename class_name    x    y    w    h
0      000005.jpg      chair  131  164   27   76
1      000005.jpg      chair   94  190   39   65
2      000005.jpg      chair   16  185   28   78
3      000005.jpg      chair  120  147   24   63
4      000005.jpg      chair  132  121   16   20
...           ...        ...  ...  ...  ...  ...
15657  009958.jpg     person   53   82   27  128
15658  009958.jpg     person   50   55   32   57
15659  009958.jpg    bicycle   57  147   45  131
15660  009959.jpg        car  117   98   62   27
15661  009961.jpg        dog  103  105  145  204

[15662 rows x 6 columns]

In [43]:
df.iloc[0].filename

'000005.jpg'

In [44]:
groups = df.groupby("filename")

In [46]:
for filename, group in groups:
    print(filename, group)

000005.jpg      filename class_name    x    y   w   h
0  000005.jpg      chair  131  164  27  76
1  000005.jpg      chair   94  190  39  65
2  000005.jpg      chair   16  185  28  78
3  000005.jpg      chair  120  147  24  63
4  000005.jpg      chair  132  121  16  20
000007.jpg      filename class_name    x    y    w    h
5  000007.jpg        car  144  128  161  188
000009.jpg      filename class_name    x    y   w   h
6  000009.jpg      horse   76  150  90  94
7  000009.jpg     person   85  127  35  85
8  000009.jpg     person  137  159  19  78
9  000009.jpg     person  124  157  17  78
000012.jpg       filename class_name    x    y   w    h
10  000012.jpg        car  114  123  87  116
000016.jpg       filename class_name    x    y    w    h
11  000016.jpg    bicycle  133  122  143  180
000017.jpg       filename class_name    x    y    w    h
12  000017.jpg     person  108   80   44   84
13  000017.jpg      horse  115  127  146  159
000019.jpg       filename class_name    x    y    w    h
14  000019.jpg        cat  160  103  113  100
15  000019.jpg        cat   62  111  114   87
000020.jpg       filename class_name    x    y    w    h
16  000020.jpg        car  121  126  202  120
000021.jpg       filename class_name    x    y    w    h
17  000021.jpg        dog   61  140  121   69
18  000021.jpg     person  182  116   84  200
19  000021.jpg     person   72  100   83  127
20  000021.jpg     person   51  134   87  107
000023.jpg       filename class_name    x    y    w    h
21  000023.jpg    bicycle   85  164  158  121
22  000023.jpg    bicycle  189  161   70  125
23  000023.jpg    bicycle   31  152   59  144
24  000023.jpg     person   40   83   77  165
25  000023.jpg     person   82  104  161  206
26  000023.jpg     person  187  109   73  217
000024.jpg       filename class_name    x    y    w   h
27  000024.jpg      train  153  138  131  55
000026.jpg       filename class_name   x    y    w   h
28  000026.jpg        car  96  113  111  59
000030.jpg       filename class_name    x    y   w   h
29  000030.jpg    bicycle   48  148  65  50
30  000030.jpg     person   45  135  44  79
31  000030.jpg     person  167  128  69  91
000032.jpg       filename class_name    x    y    w   h
32  000032.jpg  aeroplane  107  104  121  84
33  000032.jpg  aeroplane   74   84   29  28
34  000032.jpg     person   91  163    8  39
35  000032.jpg     person   16  170    8  39
000033.jpg       filename class_name    x    y    w   h
36  000033.jpg  aeroplane  114  113  220  95
37  000033.jpg  aeroplane  202  130   27  16
38  000033.jpg  aeroplane  165  126   39  21
000034.jpg       filename class_name    x    y    w    h
39  000034.jpg      train  148  127  152  104
40  000034.jpg      train  147   86  119   34
000035.jpg       filename   class_name    x    y    w    h
41  000035.jpg       person   43  136   85  158
42  000035.jpg       person  153  124  111  131
43  000035.jpg       person  217  153   14   73
44  000035.jpg  diningtable  113  203  223   42
000036.jpg       filename class_name    x   y    w    h
45  000036.jpg        dog  117  95  197  119
000039.jpg       filename class_name    x    y   w    h
46  000039.jpg  tvmonitor  112  110  84  113
000041.jpg       filename class_name    x    y   w    h
47  000041.jpg  tvmonitor  178   52  31   40
48  000041.jpg     person  117  133  41  141
49  000041.jpg     person   88  132  28   65
000042.jpg       filename class_name    x    y    w    h
50  000042.jpg      train  171  109  106  176
51  000042.jpg      train   53  112  105  176
000044.jpg       filename class_name   x    y    w    h
52  000044.jpg      chair  83  111  165  221
53  000044.jpg        cat  92  106   95   75
000046.jpg       filename class_name    x    y   w   h
54  000046.jpg       bird  178  134  72  59
000047.jpg       filename class_name    x    y    w    h
55  000047.jpg        car  106  105  199  209
56  000047.jpg      chair  207  135   22   40
000048.jpg       filename class_name    x    y    w    h
57  000048.jpg       bird  104  128  139  160
58  000048.jpg     person   91  112  179  224
000050.jpg       filename class_name    x    y    w    h
59  000050.jpg      chair  201  122   39   61
60  000050.jpg      chair  131   89   17   24
61  000050.jpg     bottle  166  136    9   44
62  000050.jpg     bottle  184  124   10   32
63  000050.jpg     bottle  126  128    9   40
64  000050.jpg     bottle  136  125    8   39
65  000050.jpg     person   81  141  101  167
66  000050.jpg     person   20  120   39  156
67  000050.jpg     person   99   79   33   77
68  000050.jpg     person  155   90   54  104
000051.jpg       filename class_name    x    y    w    h
69  000051.jpg  motorbike  191  153   66  142
70  000051.jpg  motorbike  119   73  144  146
71  000051.jpg     person  197   76   22   80
000052.jpg       filename   class_name    x    y   w   h
72  000052.jpg  pottedplant  195  166  20  21
73  000052.jpg  pottedplant  140  171  19  22
74  000052.jpg  pottedplant   92  172  20  24
75  000052.jpg  pottedplant   34  174  21  20
76  000052.jpg  pottedplant   38   77  20  24
77  000052.jpg  pottedplant   92   75  18  23
000060.jpg       filename class_name    x    y    w    h
78  000060.jpg        car   96  158  191  131
79  000060.jpg        car  108  100  214  116
80  000060.jpg        car   95   56  189   76
81  000060.jpg        car  112   47  185   85
82  000060.jpg        car  151   35  124   62
000061.jpg       filename class_name    x    y   w    h
83  000061.jpg       boat  159   98  73  180
84  000061.jpg       boat  104  157  43   26
000063.jpg       filename class_name    x    y    w    h
85  000063.jpg        dog  112  116  115   96
86  000063.jpg      chair  113  112  158  223
000064.jpg       filename class_name    x    y    w    h
87  000064.jpg       bird  102  117  203  214
000065.jpg       filename class_name   x    y    w    h
88  000065.jpg        dog  90  146  177  154
000066.jpg       filename class_name    x    y   w   h
89  000066.jpg     person   98  125   9  26
90  000066.jpg     person  116  132  14  46
91  000066.jpg     person  126  134  12  42
000072.jpg       filename class_name    x    y    w    h
92  000072.jpg  motorbike  125  122  197  180
93  000072.jpg  motorbike  122   40  200   42
000073.jpg       filename   class_name    x    y    w    h
94  000073.jpg  pottedplant  148  135  152  142
95  000073.jpg  pottedplant   20  137   37  137
96  000073.jpg         boat  193  109   63   79
97  000073.jpg       person   50  144   74  160
000077.jpg       filename class_name    x    y    w    h
98  000077.jpg        cat  166  112  116  223
99  000077.jpg        cat   69  112  136  223
000078.jpg        filename class_name    x    y    w    h
100  000078.jpg        dog  110  130  206  180
101  000078.jpg        dog  119   75  154  105
000081.jpg        filename class_name    x    y    w    h
102  000081.jpg       sofa  156  148  102   83
103  000081.jpg       sofa   51  164   95  105
104  000081.jpg     person  121  130   64   50
105  000081.jpg     person  179  138   46   81
106  000081.jpg     person   52  166   49  115
107  000081.jpg     person   23  127   20   32
108  000081.jpg     person  164  195   60   59
109  000081.jpg     person  118  183   61   77
110  000081.jpg     person  133  212   24   24
000083.jpg        filename class_name    x    y    w    h
111  000083.jpg        car  125  115  151  186
112  000083.jpg     person  183   46   25   89
113  000083.jpg     person   74   43   25   68
114  000083.jpg     person   17   75   33  124
115  000083.jpg     person   39   69   24   73
116  000083.jpg     person   26   72   23   75
000089.jpg        filename class_name    x    y    w    h
117  000089.jpg     person   45  108   73  208
118  000089.jpg     person  118  176  148   95
119  000089.jpg     person  176  152   55  135
120  000089.jpg      chair   76  102  132  144
000091.jpg        filename class_name   x    y   w   h
121  000091.jpg        car  72  157  31  26
122  000091.jpg        car  42  154  11  12
123  000091.jpg        car  49  157  16  14
000093.jpg        filename class_name    x    y    w    h
124  000093.jpg        dog  116  125   76   85
125  000093.jpg      chair  124  113  200  221
000095.jpg        filename class_name    x    y    w    h
126  000095.jpg      train  103  117  188  162
127  000095.jpg      train   26  124   51   76
000099.jpg        filename class_name   x   y    w    h
128  000099.jpg        cat  73  98  142  105
000101.jpg        filename class_name    x    y    w    h
129  000101.jpg      chair  119   82   73   86
130  000101.jpg     person   99  134  161  181
000102.jpg        filename class_name    x    y    w   h
131  000102.jpg       sofa  205  146   38  83
132  000102.jpg       sofa  106  122  103  84
000104.jpg        filename class_name    x    y    w    h
133  000104.jpg  tvmonitor  202  126   43  104
134  000104.jpg     person  164  137   68  174
135  000104.jpg     person   64  114  126  219
000107.jpg        filename class_name    x    y   w   h
136  000107.jpg      sheep  218  120  13  32
137  000107.jpg        cow  141   98  17  17
138  000107.jpg      sheep  112   94   8  14
000109.jpg        filename class_name    x    y    w    h
139  000109.jpg       bird  112  109  208  197
000110.jpg        filename class_name   x    y   w   h
140  000110.jpg     person  42  163  14  48
141  000110.jpg     person  31  172  14  67
142  000110.jpg     person  18  160   9  42
000112.jpg        filename class_name    x    y    w   h
143  000112.jpg        dog  117  112  139  69
144  000112.jpg      chair  203   81   20  16
000113.jpg        filename class_name    x    y   w    h
145  000113.jpg     person  141  122  34  107
000117.jpg        filename class_name    x    y    w    h
146  000117.jpg  aeroplane  112  110  223  163
000118.jpg        filename class_name    x    y   w    h
147  000118.jpg        cat  100  141  52  166
000120.jpg        filename class_name    x    y    w   h
148  000120.jpg        dog  113  111  168  87
000121.jpg        filename class_name    x   y    w    h
149  000121.jpg  tvmonitor  163  88  100  143
150  000121.jpg  tvmonitor   61  90  103  146
000122.jpg        filename class_name    x    y    w    h
151  000122.jpg        cat  110  115  186  212
000123.jpg        filename class_name   x    y    w    h
152  000123.jpg      train  80  109  160  188
000125.jpg        filename class_name    x    y   w   h
153  000125.jpg    bicycle  207  147  34  34
154  000125.jpg     person  202  123  14  21
155  000125.jpg     person  179  144  15  38
156  000125.jpg     person  165  146  13  38
000129.jpg        filename class_name    x    y    w    h
157  000129.jpg    bicycle  109  157  124  134
158  000129.jpg    bicycle  196  166   56  116
159  000129.jpg    bicycle   23  130   44  131
160  000129.jpg     person   22   82   44  162
161  000129.jpg     person  116  104  133  207
162  000129.jpg     person  197  113   55  210
000130.jpg        filename class_name    x   y    w    h
163  000130.jpg       boat  113  75  222  148
000131.jpg        filename class_name    x    y    w    h
164  000131.jpg        car  107  123  212  112
165  000131.jpg     person   66   94   22   19
166  000131.jpg     person   92   92   19   22
000132.jpg        filename class_name   x    y    w    h
167  000132.jpg        bus  72  114  106  158
000133.jpg        filename class_name    x    y    w    h
168  000133.jpg     person  120  116  167  216
169  000133.jpg      horse  119  163  102  122
170  000133.jpg     person   24   23   27   45
171  000133.jpg      horse   45   36   48   21
000134.jpg        filename class_name    x    y    w    h
172  000134.jpg        car  109  134  218  130
000138.jpg        filename class_name    x    y   w    h
173  000138.jpg     person   36  115  66  155
174  000138.jpg     person   96  107  62  135
175  000138.jpg     person  149  130  97  188
176  000138.jpg     person  193  144  61  159
000140.jpg        filename class_name    x    y    w    h
177  000140.jpg        dog  110  125  125   86
178  000140.jpg       sofa  112  144  223  161
000141.jpg        filename class_name   x    y    w    h
179  000141.jpg       bird  99  120  176  183
000142.jpg        filename class_name    x    y    w    h
180  000142.jpg        car  110  104  197  111
000143.jpg        filename class_name    x    y    w    h
181  000143.jpg        cat  150  127  148  193
000146.jpg        filename class_name    x    y   w   h
182  000146.jpg     person  122  138  58  90
000147.jpg        filename class_name    x   y   w   h
183  000147.jpg      chair   22  84  14  28
184  000147.jpg      chair   43  88  17  24
185  000147.jpg      chair   72  92  13  17
186  000147.jpg      chair  106  96   9  15
187  000147.jpg      chair  141  94  11  17
188  000147.jpg      chair  174  92  13  22
189  000147.jpg      chair  202  88  13  25
000150.jpg        filename class_name    x    y   w    h
190  000150.jpg      horse  113  115  60  125
191  000150.jpg     person  164   54  12   36
192  000150.jpg     person  191   54   9   39
193  000150.jpg     person  217   51   7   30
194  000150.jpg     person  222   51   5   33
000153.jpg        filename class_name    x    y   w   h
195  000153.jpg        car  133  101  54  26
196  000153.jpg        car   68   38  13   8
197  000153.jpg        car   37   71  32   7
198  000153.jpg        car   15   69  27   8
000154.jpg        filename class_name    x    y    w    h
199  000154.jpg       boat   95  115  138  128
200  000154.jpg       boat  201  137    8   13
000156.jpg        filename class_name    x    y    w    h
201  000156.jpg       sofa   95  127  152  167
202  000156.jpg        car  208   74   29   24
203  000156.jpg        car  188   77   14   17
000158.jpg        filename class_name    x   y   w   h
204  000158.jpg       bird  104  87  32  74
000159.jpg        filename class_name    x    y    w    h
205  000159.jpg     person  116   58   23   51
206  000159.jpg        car  112  117  223  213
000161.jpg        filename class_name    x    y    w    h
207  000161.jpg        car  123  122  153  204
208  000161.jpg        car   42  139   24   53
000162.jpg        filename class_name    x    y   w    h
209  000162.jpg  tvmonitor  154  157  33   43
210  000162.jpg     person  113  153  51  135
000163.jpg        filename class_name    x    y    w    h
211  000163.jpg     person   81   91  115  159
212  000163.jpg  motorbike  108  131  193  149
000164.jpg        filename class_name    x    y    w    h
213  000164.jpg  motorbike  108  150  114  116
214  000164.jpg     person  165  125   69  192
000165.jpg        filename class_name    x    y    w    h
215  000165.jpg     person  132  128  184  193
000169.jpg        filename class_name    x    y    w    h
216  000169.jpg        car  113  105  205  172
217  000169.jpg     person   59   18   26   32
218  000169.jpg        car  210   68   27  104
219  000169.jpg     person  193   40   11   28
220  000169.jpg     person  211   36   15   24
221  000169.jpg        car   26   60   41   58
000170.jpg        filename class_name    x    y    w    h
222  000170.jpg     bottle   44   79   10   39
223  000170.jpg     bottle   26   88   14   40
224  000170.jpg     bottle  151  106   13   35
225  000170.jpg     bottle  195  105    8   23
226  000170.jpg     person   10   89   18   69
227  000170.jpg     person  104  119  205  205
000171.jpg        filename class_name    x    y    w    h
228  000171.jpg        dog   39  156   76   52
229  000171.jpg     person  140  115  168  211
000173.jpg        filename class_name    x    y    w    h
230  000173.jpg     person  107   84   93  109
231  000173.jpg      horse  113  123  102  187
000174.jpg        filename class_name    x    y    w    h
232  000174.jpg     person  127  114  127  221
000177.jpg        filename   class_name    x    y    w    h
233  000177.jpg  diningtable  116  157  180  133
234  000177.jpg       person  189  157   70  134
235  000177.jpg       person  174  134   60  165
236  000177.jpg       person  156   90   39   70
237  000177.jpg       person  138   78   26   50
238  000177.jpg       person   95   69   44   57
239  000177.jpg       person   65   78   17   43
240  000177.jpg       person   52   95   37   86
241  000177.jpg       person   22  145   43  157
000180.jpg        filename class_name    x    y    w    h
242  000180.jpg        car  114  139  216  147
000184.jpg        filename class_name    x    y    w    h
243  000184.jpg       boat  140   89   22   51
244  000184.jpg       boat  174   99   13   26
245  000184.jpg       boat  210  103   10   22
246  000184.jpg       boat   70  112  139  223
000187.jpg        filename class_name   x    y    w    h
247  000187.jpg  tvmonitor  54  129  107  144
000189.jpg        filename class_name    x    y    w    h
248  000189.jpg       bird  117  115  177  183
000190.jpg        filename class_name    x    y   w   h
249  000190.jpg        bus  207  140  33  45
250  000190.jpg        bus  125  142  39  25
251  000190.jpg        bus   69  146  13  38
252  000190.jpg        bus   45  155  45  59
253  000190.jpg        bus   13  156  24  62
254  000190.jpg     person  143  152   5  17
255  000190.jpg     person  126  152   3  16
256  000190.jpg     person  123  150   2   7
257  000190.jpg     person  117  153   4  17
258  000190.jpg     person  113  153   4  14
259  000190.jpg     person   94  154   4  15
260  000190.jpg     person   86  155   4  20
261  000190.jpg     person   81  155   3  17
000192.jpg        filename class_name    x    y    w    h
262  000192.jpg     person  106  131  108  186
263  000192.jpg      chair   11  175   21   97
000193.jpg        filename class_name    x    y    w    h
264  000193.jpg     person  130  113  188  222
265  000193.jpg     person   51  121  101  207
266  000193.jpg       sofa  112  149  223  149
000194.jpg        filename class_name    x    y    w    h
267  000194.jpg      horse  114  130  107  188
268  000194.jpg     person  111   78   62  117
269  000194.jpg     person  202  104   13   55
000198.jpg        filename class_name    x    y   w   h
270  000198.jpg      train  100  125  56  70
000200.jpg        filename class_name    x    y   w    h
271  000200.jpg     person   29   84  34  133
272  000200.jpg     person   43  136  73  175
273  000200.jpg     person   88  122  44  203
274  000200.jpg     person  140  121  78  207
275  000200.jpg     person  200  118  49  212
276  000200.jpg     bottle  169  207  11   33
277  000200.jpg     bottle  110  160  13   58
000203.jpg        filename class_name   x    y   w    h
278  000203.jpg      chair  49  167  52  112
000207.jpg        filename class_name   x    y   w   h
279  000207.jpg        bus  38  118  75  52
000208.jpg        filename   class_name    x    y    w   h
280  000208.jpg  diningtable   37  116   74  79
281  000208.jpg        chair  186  179   76  91
282  000208.jpg        chair   67   99   28  63
283  000208.jpg        chair   43  113   32  79
284  000208.jpg        chair    8  128   14  36
285  000208.jpg         sofa  143  137  104  94
000209.jpg        filename class_name   x    y    w    h
286  000209.jpg        cat  93  135  173  179
000210.jpg        filename class_name    x    y   w   h
287  000210.jpg        car  175  131  12   8
288  000210.jpg     person  204  134  11  14
289  000210.jpg     person  147  132   5   7
290  000210.jpg     person   12  136  10  16
000211.jpg        filename class_name   x    y   w   h
291  000211.jpg        cow  65  182  88  52
000214.jpg        filename class_name    x    y    w    h
292  000214.jpg      horse  158  112  132  223
000215.jpg        filename class_name    x    y   w    h
293  000215.jpg        cat  108  118  87  158
000218.jpg        filename class_name    x    y    w    h
294  000218.jpg        dog  142  107   58  128
295  000218.jpg      chair   69   59   43  116
296  000218.jpg     person   57   75  113  149
000219.jpg        filename class_name    x    y    w   h

In [50]:
filenames = list(df["filename"].unique())
filenames

['000005.jpg',
 '000007.jpg',
 '000009.jpg',
 '000012.jpg',
 '000016.jpg',
 '000017.jpg',
 '000019.jpg',
 '000020.jpg',
 '000021.jpg',
 '000023.jpg',
 '000024.jpg',
 '000026.jpg',
 '000030.jpg',
 '000032.jpg',
 '000033.jpg',
 '000034.jpg',
 '000035.jpg',
 '000036.jpg',
 '000039.jpg',
 '000041.jpg',
 '000042.jpg',
 '000044.jpg',
 '000046.jpg',
 '000047.jpg',
 '000048.jpg',
 '000050.jpg',
 '000051.jpg',
 '000052.jpg',
 '000060.jpg',
 '000061.jpg',
 '000063.jpg',
 '000064.jpg',
 '000065.jpg',
 '000066.jpg',
 '000072.jpg',
 '000073.jpg',
 '000077.jpg',
 '000078.jpg',
 '000081.jpg',
 '000083.jpg',
 '000089.jpg',
 '000091.jpg',
 '000093.jpg',
 '000095.jpg',
 '000099.jpg',
 '000101.jpg',
 '000102.jpg',
 '000104.jpg',
 '000107.jpg',
 '000109.jpg',
 '000110.jpg',
 '000112.jpg',
 '000113.jpg',
 '000117.jpg',
 '000118.jpg',
 '000120.jpg',
 '000121.jpg',
 '000122.jpg',
 '000123.jpg',
 '000125.jpg',
 '000129.jpg',
 '000130.jpg',
 '000131.jpg',
 '000132.jpg',
 '000133.jpg',
 '000134.jpg',
 '000138.jpg',
 '000140.jpg',
 '000141.jpg',
 '000142.jpg',
 '000143.jpg',
 '000146.jpg',
 '000147.jpg',
 '000150.jpg',
 '000153.jpg',
 '000154.jpg',
 '000156.jpg',
 '000158.jpg',
 '000159.jpg',
 '000161.jpg',
 '000162.jpg',
 '000163.jpg',
 '000164.jpg',
 '000165.jpg',
 '000169.jpg',
 '000170.jpg',
 '000171.jpg',
 '000173.jpg',
 '000174.jpg',
 '000177.jpg',
 '000180.jpg',
 '000184.jpg',
 '000187.jpg',
 '000189.jpg',
 '000190.jpg',
 '000192.jpg',
 '000193.jpg',
 '000194.jpg',
 '000198.jpg',
 '000200.jpg',
 '000203.jpg',
 '000207.jpg',
 '000208.jpg',
 '000209.jpg',
 '000210.jpg',
 '000211.jpg',
 '000214.jpg',
 '000215.jpg',
 '000218.jpg',
 '000219.jpg',
 '000220.jpg',
 '000221.jpg',
 '000222.jpg',
 '000224.jpg',
 '000225.jpg',
 '000228.jpg',
 '000229.jpg',
 '000232.jpg',
 '000233.jpg',
 '000235.jpg',
 '000236.jpg',
 '000241.jpg',
 '000242.jpg',
 '000244.jpg',
 '000245.jpg',
 '000246.jpg',
 '000249.jpg',
 '000250.jpg',
 '000251.jpg',
 '000256.jpg',
 '000257.jpg',
 '000259.jpg',
 '000262.jpg',
 '000263.jpg',
 '000266.jpg',
 '000268.jpg',
 '000269.jpg',
 '000270.jpg',
 '000275.jpg',
 '000276.jpg',
 '000278.jpg',
 '000282.jpg',
 '000285.jpg',
 '000288.jpg',
 '000289.jpg',
 '000294.jpg',
 '000296.jpg',
 '000298.jpg',
 '000302.jpg',
 '000303.jpg',
 '000304.jpg',
 '000305.jpg',
 '000306.jpg',
 '000307.jpg',
 '000308.jpg',
 '000311.jpg',
 '000312.jpg',
 '000317.jpg',
 '000318.jpg',
 '000320.jpg',
 '000321.jpg',
 '000322.jpg',
 '000323.jpg',
 '000325.jpg',
 '000328.jpg',
 '000329.jpg',
 '000331.jpg',
 '000332.jpg',
 '000334.jpg',
 '000336.jpg',
 '000337.jpg',
 '000338.jpg',
 '000340.jpg',
 '000343.jpg',
 '000344.jpg',
 '000347.jpg',
 '000349.jpg',
 '000352.jpg',
 '000354.jpg',
 '000355.jpg',
 '000359.jpg',
 '000363.jpg',
 '000367.jpg',
 '000370.jpg',
 '000372.jpg',
 '000373.jpg',
 '000374.jpg',
 '000379.jpg',
 '000380.jpg',
 '000381.jpg',
 '000382.jpg',
 '000387.jpg',
 '000391.jpg',
 '000394.jpg',
 '000395.jpg',
 '000396.jpg',
 '000400.jpg',
 '000403.jpg',
 '000404.jpg',
 '000406.jpg',
 '000407.jpg',
 '000408.jpg',
 '000411.jpg',
 '000416.jpg',
 '000417.jpg',
 '000419.jpg',
 '000420.jpg',
 '000424.jpg',
 '000427.jpg',
 '000428.jpg',
 '000430.jpg',
 '000431.jpg',
 '000433.jpg',
 '000435.jpg',
 '000438.jpg',
 '000439.jpg',
 '000443.jpg',
 '000446.jpg',
 '000448.jpg',
 '000450.jpg',
 '000454.jpg',
 '000459.jpg',
 '000460.jpg',
 '000461.jpg',
 '000462.jpg',
 '000463.jpg',
 '000464.jpg',
 '000468.jpg',
 '000469.jpg',
 '000470.jpg',
 '000474.jpg',
 '000476.jpg',
 '000477.jpg',
 '000480.jpg',
 '000482.jpg',
 '000483.jpg',
 '000484.jpg',
 '000486.jpg',
 '000489.jpg',
 '000491.jpg',
 '000492.jpg',
 '000494.jpg',
 '000496.jpg',
 '000498.jpg',
 '000499.jpg',
 '000500.jpg',
 '000501.jpg',
 '000503.jpg',
 '000508.jpg',
 '000509.jpg',
 '000513.jpg',
 '000514.jpg',
 '000515.jpg',
 '000516.jpg',
 '000518.jpg',
 '000519.jpg',
 '000520.jpg',
 '000522.jpg',
 '000523.jpg',
 '000524.jpg',
 '000525.jpg',
 '000526.jpg',
 '000528.jpg',
 '000530.jpg',
 '000531.jpg',
 '000535.jpg',
 '000537.jpg',
 '000540.jpg',
 '000541.jpg',
 '000543.jpg',
 '000544.jpg',
 '000545.jpg',
 '000549.jpg',
 '000550.jpg',
 '000552.jpg',
 '000554.jpg',
 '000555.jpg',
 '000559.jpg',
 '000563.jpg',
 '000564.jpg',
 '000565.jpg',
 '000577.jpg',
 '000579.jpg',
 '000581.jpg',
 '000582.jpg',
 '000583.jpg',
 '000588.jpg',
 '000589.jpg',
 '000590.jpg',
 '000591.jpg',
 '000592.jpg',
 '000597.jpg',
 '000598.jpg',
 '000599.jpg',
 '000601.jpg',
 '000605.jpg',
 '000608.jpg',
 '000609.jpg',
 '000610.jpg',
 '000612.jpg',
 '000613.jpg',
 '000619.jpg',
 '000620.jpg',
 '000622.jpg',
 '000625.jpg',
 '000626.jpg',
 '000628.jpg',
 '000632.jpg',
 '000633.jpg',
 '000635.jpg',
 '000637.jpg',
 '000645.jpg',
 '000647.jpg',
 '000648.jpg',
 '000653.jpg',
 '000654.jpg',
 '000656.jpg',
 '000657.jpg',
 '000660.jpg',
 '000661.jpg',
 '000663.jpg',
 '000667.jpg',
 '000671.jpg',
 '000672.jpg',
 '000675.jpg',
 '000676.jpg',
 '000677.jpg',
 '000680.jpg',
 '000682.jpg',
 '000684.jpg',
 '000685.jpg',
 '000686.jpg',
 '000688.jpg',
 '000689.jpg',
 '000690.jpg',
 '000694.jpg',
 '000695.jpg',
 '000699.jpg',
 '000700.jpg',
 '000702.jpg',
 '000705.jpg',
 '000707.jpg',
 '000709.jpg',
 '000710.jpg',
 '000711.jpg',
 '000712.jpg',
 '000713.jpg',
 '000714.jpg',
 '000717.jpg',
 '000720.jpg',
 '000726.jpg',
 '000728.jpg',
 '000729.jpg',
 '000730.jpg',
 '000731.jpg',
 '000733.jpg',
 '000738.jpg',
 '000739.jpg',
 '000740.jpg',
 '000742.jpg',
 '000746.jpg',
 '000748.jpg',
 '000750.jpg',
 '000752.jpg',
 '000753.jpg',
 '000754.jpg',
 '000755.jpg',
 '000756.jpg',
 '000760.jpg',
 '000761.jpg',
 '000763.jpg',
 '000764.jpg',
 '000767.jpg',
 '000768.jpg',
 '000770.jpg',
 '000771.jpg',
 '000772.jpg',
 '000774.jpg',
 '000776.jpg',
 '000777.jpg',
 '000780.jpg',
 '000782.jpg',
 '000786.jpg',
 '000787.jpg',
 '000791.jpg',
 '000793.jpg',
 '000794.jpg',
 '000796.jpg',
 '000797.jpg',
 '000799.jpg',
 '000800.jpg',
 '000802.jpg',
 '000804.jpg',
 '000805.jpg',
 '000806.jpg',
 '000808.jpg',
 '000810.jpg',
 '000812.jpg',
 '000814.jpg',
 '000815.jpg',
 '000816.jpg',
 '000818.jpg',
 '000820.jpg',
 '000822.jpg',
 '000823.jpg',
 '000826.jpg',
 '000827.jpg',
 '000828.jpg',
 '000829.jpg',
 '000830.jpg',
 '000831.jpg',
 '000832.jpg',
 '000834.jpg',
 '000842.jpg',
 '000843.jpg',
 '000845.jpg',
 '000847.jpg',
 '000848.jpg',
 '000849.jpg',
 '000850.jpg',
 '000851.jpg',
 '000854.jpg',
 '000855.jpg',
 '000857.jpg',
 '000859.jpg',
 '000860.jpg',
 '000862.jpg',
 '000863.jpg',
 '000865.jpg',
 '000867.jpg',
 '000868.jpg',
 '000871.jpg',
 '000872.jpg',
 '000874.jpg',
 '000876.jpg',
 '000878.jpg',
 '000879.jpg',
 '000880.jpg',
 '000882.jpg',
 '000885.jpg',
 '000887.jpg',
 '000888.jpg',
 '000889.jpg',
 '000892.jpg',
 '000895.jpg',
 '000896.jpg',
 '000898.jpg',
 '000899.jpg',
 '000900.jpg',
 '000902.jpg',
 '000903.jpg',
 '000904.jpg',
 '000906.jpg',
 '000908.jpg',
 '000911.jpg',
 '000912.jpg',
 '000915.jpg',
 '000917.jpg',
 '000918.jpg',
 '000919.jpg',
 '000920.jpg',
 '000921.jpg',
 '000923.jpg',
 '000926.jpg',
 '000929.jpg',
 '000931.jpg',
 '000934.jpg',
 '000935.jpg',
 '000936.jpg',
 '000937.jpg',
 '000943.jpg',
 '000946.jpg',
 '000947.jpg',
 '000948.jpg',
 '000949.jpg',
 '000950.jpg',
 '000951.jpg',
 '000954.jpg',
 '000958.jpg',
 '000962.jpg',
 '000964.jpg',
 '000965.jpg',
 '000966.jpg',
 '000967.jpg',
 '000971.jpg',
 '000972.jpg',
 '000973.jpg',
 '000977.jpg',
 '000980.jpg',
 '000982.jpg',
 '000987.jpg',
 '000989.jpg',
 '000991.jpg',
 '000993.jpg',
 '000996.jpg',
 '000997.jpg',
 '000999.jpg',
 '001001.jpg',
 '001002.jpg',
 '001004.jpg',
 '001008.jpg',
 '001009.jpg',
 '001010.jpg',
 '001011.jpg',
 '001012.jpg',
 '001014.jpg',
 '001015.jpg',
 '001017.jpg',
 '001018.jpg',
 '001024.jpg',
 '001027.jpg',
 '001028.jpg',
 '001036.jpg',
 '001041.jpg',
 '001042.jpg',
 '001043.jpg',
 '001045.jpg',
 '001050.jpg',
 '001052.jpg',
 '001053.jpg',
 '001056.jpg',
 '001057.jpg',
 '001060.jpg',
 '001061.jpg',
 '001062.jpg',
 '001064.jpg',
 '001066.jpg',
 '001068.jpg',
 '001069.jpg',
 '001071.jpg',
 '001072.jpg',
 '001073.jpg',
 '001074.jpg',
 '001077.jpg',
 '001078.jpg',
 '001079.jpg',
 '001082.jpg',
 '001083.jpg',
 '001084.jpg',
 '001091.jpg',
 '001092.jpg',
 '001093.jpg',
 '001097.jpg',
 '001101.jpg',
 '001102.jpg',
 '001104.jpg',
 '001106.jpg',
 '001107.jpg',
 '001109.jpg',
 '001110.jpg',
 '001112.jpg',
 '001113.jpg',
 '001119.jpg',
 '001121.jpg',
 '001124.jpg',
 '001125.jpg',
 '001127.jpg',
 '001129.jpg',
 '001130.jpg',
 '001136.jpg',
 '001137.jpg',
 '001140.jpg',
 '001142.jpg',
 '001143.jpg',
 '001144.jpg',
 '001145.jpg',
 '001147.jpg',
 '001148.jpg',
 '001149.jpg',
 '001151.jpg',
 '001152.jpg',
 '001154.jpg',
 '001156.jpg',
 '001158.jpg',
 '001160.jpg',
 '001161.jpg',
 '001164.jpg',
 '001166.jpg',
 '001168.jpg',
 '001170.jpg',
 '001171.jpg',
 '001172.jpg',
 '001174.jpg',
 '001175.jpg',
 '001176.jpg',
 '001182.jpg',
 '001184.jpg',
 '001185.jpg',
 '001186.jpg',
 '001187.jpg',
 '001191.jpg',
 '001192.jpg',
 '001194.jpg',
 '001199.jpg',
 '001200.jpg',
 '001201.jpg',
 '001203.jpg',
 '001204.jpg',
 '001205.jpg',
 '001206.jpg',
 '001207.jpg',
 '001209.jpg',
 '001211.jpg',
 '001212.jpg',
 '001214.jpg',
 '001215.jpg',
 '001221.jpg',
 '001224.jpg',
 '001225.jpg',
 '001226.jpg',
 '001229.jpg',
 '001230.jpg',
 '001231.jpg',
 '001233.jpg',
 '001234.jpg',
 '001236.jpg',
 '001237.jpg',
 '001239.jpg',
 '001240.jpg',
 '001241.jpg',
 '001247.jpg',
 '001248.jpg',
 '001250.jpg',
 '001254.jpg',
 '001258.jpg',
 '001259.jpg',
 '001260.jpg',
 '001263.jpg',
 '001265.jpg',
 '001266.jpg',
 '001268.jpg',
 '001269.jpg',
 '001270.jpg',
 '001272.jpg',
 '001273.jpg',
 '001274.jpg',
 '001277.jpg',
 '001279.jpg',
 '001281.jpg',
 '001284.jpg',
 '001286.jpg',
 '001287.jpg',
 '001288.jpg',
 '001289.jpg',
 '001290.jpg',
 '001292.jpg',
 '001293.jpg',
 '001294.jpg',
 '001298.jpg',
 '001299.jpg',
 '001304.jpg',
 '001309.jpg',
 '001310.jpg',
 '001311.jpg',
 '001312.jpg',
 '001314.jpg',
 '001315.jpg',
 '001316.jpg',
 '001323.jpg',
 '001324.jpg',
 '001325.jpg',
 '001326.jpg',
 '001327.jpg',
 '001330.jpg',
 '001332.jpg',
 '001333.jpg',
 '001334.jpg',
 '001337.jpg',
 '001341.jpg',
 '001343.jpg',
 '001345.jpg',
 '001346.jpg',
 '001348.jpg',
 '001350.jpg',
 '001352.jpg',
 '001360.jpg',
 '001361.jpg',
 '001362.jpg',
 '001364.jpg',
 '001365.jpg',
 '001371.jpg',
 '001375.jpg',
 '001378.jpg',
 '001383.jpg',
 '001384.jpg',
 '001385.jpg',
 '001386.jpg',
 '001387.jpg',
 '001388.jpg',
 '001390.jpg',
 '001393.jpg',
 '001395.jpg',
 '001397.jpg',
 '001400.jpg',
 '001402.jpg',
 '001404.jpg',
 '001405.jpg',
 '001406.jpg',
 '001408.jpg',
 '001409.jpg',
 '001413.jpg',
 '001414.jpg',
 '001418.jpg',
 '001420.jpg',
 '001421.jpg',
 '001426.jpg',
 '001427.jpg',
 '001430.jpg',
 '001432.jpg',
 '001434.jpg',
 '001436.jpg',
 '001439.jpg',
 '001441.jpg',
 '001442.jpg',
 '001443.jpg',
 '001444.jpg',
 '001445.jpg',
 '001450.jpg',
 '001451.jpg',
 '001453.jpg',
 '001455.jpg',
 '001457.jpg',
 '001460.jpg',
 '001463.jpg',
 '001464.jpg',
 '001465.jpg',
 '001466.jpg',
 '001467.jpg',
 '001468.jpg',
 '001470.jpg',
 '001472.jpg',
 '001475.jpg',
 '001479.jpg',
 '001480.jpg',
 '001481.jpg',
 '001483.jpg',
 '001484.jpg',
 '001485.jpg',
 '001486.jpg',
 '001488.jpg',
 '001490.jpg',
 '001492.jpg',
 '001493.jpg',
 '001494.jpg',
 '001497.jpg',
 '001498.jpg',
 '001499.jpg',
 '001501.jpg',
 '001504.jpg',
 '001509.jpg',
 '001510.jpg',
 '001512.jpg',
 '001514.jpg',
 '001515.jpg',
 '001517.jpg',
 '001521.jpg',
 '001522.jpg',
 '001523.jpg',
 '001524.jpg',
 '001526.jpg',
 '001528.jpg',
 '001529.jpg',
 '001531.jpg',
 '001532.jpg',
 '001536.jpg',
 '001537.jpg',
 '001539.jpg',
 '001541.jpg',
 '001543.jpg',
 '001544.jpg',
 '001545.jpg',
 '001548.jpg',
 '001553.jpg',
 '001554.jpg',
 '001555.jpg',
 '001556.jpg',
 '001557.jpg',
 '001559.jpg',
 '001561.jpg',
 '001563.jpg',
 '001565.jpg',
 '001571.jpg',
 '001576.jpg',
 '001577.jpg',
 '001579.jpg',
 '001580.jpg',
 '001582.jpg',
 '001586.jpg',
 '001588.jpg',
 '001590.jpg',
 '001593.jpg',
 '001594.jpg',
 '001595.jpg',
 '001597.jpg',
 '001598.jpg',
 '001603.jpg',
 '001604.jpg',
 '001607.jpg',
 '001608.jpg',
 '001610.jpg',
 '001611.jpg',
 '001612.jpg',
 '001614.jpg',
 '001617.jpg',
 '001618.jpg',
 '001622.jpg',
 '001627.jpg',
 '001628.jpg',
 '001630.jpg',
 '001632.jpg',
 '001633.jpg',
 '001636.jpg',
 '001638.jpg',
 '001640.jpg',
 '001642.jpg',
 '001643.jpg',
 '001647.jpg',
 '001649.jpg',
 '001650.jpg',
 '001651.jpg',
 '001653.jpg',
 '001654.jpg',
 '001661.jpg',
 '001662.jpg',
 '001669.jpg',
 '001673.jpg',
 '001675.jpg',
 '001676.jpg',
 '001677.jpg',
 '001678.jpg',
 '001680.jpg',
 '001682.jpg',
 '001683.jpg',
 '001684.jpg',
 '001685.jpg',
 '001686.jpg',
 '001688.jpg',
 '001689.jpg',
 '001690.jpg',
 '001691.jpg',
 '001693.jpg',
 '001699.jpg',
 '001707.jpg',
 '001708.jpg',
 '001711.jpg',
 '001713.jpg',
 '001714.jpg',
 '001717.jpg',
 '001718.jpg',
 '001721.jpg',
 '001723.jpg',
 '001724.jpg',
 '001725.jpg',
 '001726.jpg',
 '001727.jpg',
 '001729.jpg',
 '001730.jpg',
 '001732.jpg',
 '001733.jpg',
 '001734.jpg',
 '001738.jpg',
 '001739.jpg',
 '001741.jpg',
 '001746.jpg',
 '001747.jpg',
 '001749.jpg',
 '001750.jpg',
 '001752.jpg',
 '001754.jpg',
 '001755.jpg',
 '001756.jpg',
 '001758.jpg',
 '001759.jpg',
 '001761.jpg',
 '001765.jpg',
 '001766.jpg',
 '001768.jpg',
 '001771.jpg',
 '001772.jpg',
 '001775.jpg',
 '001777.jpg',
 '001778.jpg',
 '001780.jpg',
 '001782.jpg',
 '001784.jpg',
 '001785.jpg',
 '001787.jpg',
 '001789.jpg',
 '001793.jpg',
 '001795.jpg',
 '001797.jpg',
 '001799.jpg',
 '001800.jpg',
 '001801.jpg',
 '001806.jpg',
 '001807.jpg',
 '001809.jpg',
 '001810.jpg',
 '001816.jpg',
 '001818.jpg',
 '001821.jpg',
 '001825.jpg',
 '001827.jpg',
 '001828.jpg',
 '001830.jpg',
 '001832.jpg',
 '001833.jpg',
 '001834.jpg',
 '001836.jpg',
 '001837.jpg',
 '001840.jpg',
 '001841.jpg',
 '001842.jpg',
 '001843.jpg',
 '001845.jpg',
 '001847.jpg',
 '001849.jpg',
 '001853.jpg',
 '001854.jpg',
 '001855.jpg',
 '001858.jpg',
 '001860.jpg',
 '001861.jpg',
 '001862.jpg',
 '001864.jpg',
 '001870.jpg',
 '001872.jpg',
 '001875.jpg',
 '001877.jpg',
 '001878.jpg',
 '001881.jpg',
 '001882.jpg',
 '001887.jpg',
 '001888.jpg',
 '001892.jpg',
 '001894.jpg',
 '001896.jpg',
 '001898.jpg',
 '001899.jpg',
 '001901.jpg',
 '001902.jpg',
 '001903.jpg',
 '001904.jpg',
 '001906.jpg',
 '001907.jpg',
 '001911.jpg',
 '001915.jpg',
 '001918.jpg',
 '001920.jpg',
 '001922.jpg',
 '001927.jpg',
 '001928.jpg',
 '001930.jpg',
 '001931.jpg',
 '001932.jpg',
 '001933.jpg',
 '001934.jpg',
 '001936.jpg',
 '001937.jpg',
 '001938.jpg',
 '001940.jpg',
 '001941.jpg',
 '001944.jpg',
 '001945.jpg',
 '001948.jpg',
 '001950.jpg',
 '001952.jpg',
 '001954.jpg',
 '001958.jpg',
 '001960.jpg',
 '001962.jpg',
 '001963.jpg',
 '001964.jpg',
 '001970.jpg',
 '001971.jpg',
 '001972.jpg',
 '001976.jpg',
 '001977.jpg',
 '001978.jpg',
 '001980.jpg',
 '001981.jpg',
 '001982.jpg',
 '001985.jpg',
 '001989.jpg',
 '001995.jpg',
 '001999.jpg',
 '002000.jpg',
 '002001.jpg',
 '002002.jpg',
 '002004.jpg',
 '002006.jpg',
 '002011.jpg',
 '002012.jpg',
 '002015.jpg',
 '002019.jpg',
 '002020.jpg',
 '002021.jpg',
 '002022.jpg',
 '002023.jpg',
 '002024.jpg',
 ...]

In [59]:
group = groups.get_group(filenames[0]).drop(columns=["filename"])
group

  class_name    x    y   w   h
0      chair  131  164  27  76
1      chair   94  190  39  65
2      chair   16  185  28  78
3      chair  120  147  24  63
4      chair  132  121  16  20

In [106]:
for i in group.iterrows():
    print(tuple(i[1]))

('chair', 131, 164, 27, 76)
('chair', 94, 190, 39, 65)
('chair', 16, 185, 28, 78)
('chair', 120, 147, 24, 63)
('chair', 132, 121, 16, 20)

In [66]:
len(group)

5

In [65]:
tuple(group.iloc[0])

('chair', np.int64(131), np.int64(164), np.int64(27), np.int64(76))

In [96]:
def get_labels(groups, filename):
    group = groups.get_group(filename).drop(columns=["filename"])

    objects = []
    for object_ in group:
        objects.append(tuple(object_))
    
    return objects

In [97]:
get_labels(groups, filenames[0])

[('c', 'l', 'a', 's', 's', '_', 'n', 'a', 'm', 'e'),
 ('x',),
 ('y',),
 ('w',),
 ('h',)]

### Test Dataset

In [87]:
from torchvision.io import decode_image
from torch.utils.data import Dataset

class ImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        img_df = pd.read_csv(annotations_file)
        self.filenames = list(img_df["filename"].unique()) # list of image file names
        self.groups = img_df.groupby("filename") # filename groups contain respective objects

        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        img_filename = self.filenames[idx]

        img_path = img_dir / img_filename
        image = decode_image(img_path)

        labels = get_labels(self.groups, img_filename)

        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            labels = self.target_transform(labels)

        return image, labels

In [88]:
annotations_file = Path("../data/preprocessed/trainval/annotations.csv")
img_dir = Path("../data/preprocessed/trainval/Images")
dataset = ImageDataset(annotations_file, img_dir)

In [91]:
image, label = list(iter(dataset))[0]

In [93]:
image.shape, label

(torch.Size([3, 224, 224]),
 [('chair', np.int64(131), np.int64(164), np.int64(27), np.int64(76)),
  ('chair', np.int64(94), np.int64(190), np.int64(39), np.int64(65)),
  ('chair', np.int64(16), np.int64(185), np.int64(28), np.int64(78)),
  ('chair', np.int64(120), np.int64(147), np.int64(24), np.int64(63)),
  ('chair', np.int64(132), np.int64(121), np.int64(16), np.int64(20))])